<#
install-startup-task.ps1 — registers mic_watcher.ps1 as a Windows Scheduled
Task that runs at YOUR login, in your own user context. No admin rights
required (the task is created under the current user, not SYSTEM).

Usage (from a normal, non-elevated PowerShell prompt in this directory):
    .\install-startup-task.ps1              # install (or update) and start now
    .\install-startup-task.ps1 -Uninstall   # stop and remove everything

Notes:
  - Completely windowless: the task launches the watcher through a small
    auto-generated VBScript shim (wscript.exe), which hides the PowerShell
    console entirely — no flash at logon, nothing in the taskbar. The watcher
    is only visible as a powershell.exe process in Task Manager.
  - The task only runs while you're logged in, which is exactly right: mic
    usage on this PC only matters when you're at it.
  - If you move this repo to a new path, just re-run this installer — the
    shim embeds the watcher's absolute path.
#>
param(
    [switch]$Uninstall
)

$TaskName     = 'On-Air Light Mic Watcher'
$WatcherPath  = Join-Path $PSScriptRoot 'mic_watcher.ps1'
$LauncherPath = Join-Path $env:LOCALAPPDATA 'on-air-light\run_mic_watcher.vbs'

function Stop-WatcherProcesses {
    # Kill any running watcher instances (the VBS shim exits with its child,
    # but ending the task doesn't reliably kill the child PowerShell).
    Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe'" |
        Where-Object { $_.CommandLine -like '*mic_watcher.ps1*' } |
        ForEach-Object { try { Stop-Process -Id $_.ProcessId -Force -Confirm:$false } catch {} }
}

if ($Uninstall) {
    try { Stop-ScheduledTask -TaskName $TaskName -ErrorAction Stop } catch {}
    Stop-WatcherProcesses
    try {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction Stop
        Write-Host "Removed scheduled task '$TaskName'."
    } catch {
        Write-Host "Task '$TaskName' was not installed; nothing to do."
    }
    if (Test-Path $LauncherPath) { Remove-Item -Path $LauncherPath -Force }
    exit 0
}

if (-not (Test-Path $WatcherPath)) {
    Write-Error "mic_watcher.ps1 not found next to this script ($WatcherPath)."
    exit 1
}

# Refuse to install a watcher that still points at the placeholder URL.
# Only inspect the $WebhookUrl assignment line — the placeholder string also
# appears in the watcher's own runtime guard and comments.
if (Select-String -Path $WatcherPath -Pattern '^\s*\$WebhookUrl\s*=\s*.*<pi-ip>' -Quiet) {
    Write-Error 'Edit $WebhookUrl at the top of mic_watcher.ps1 first (it still contains the <pi-ip> placeholder).'
    exit 1
}

# Generate the windowless launcher. wscript's Run with window style 0 creates
# the console hidden from the very start (unlike -WindowStyle Hidden, which
# briefly flashes one). The shim waits on the watcher and forwards its exit
# code so the task's restart-on-failure settings still work.
$launcherDir = Split-Path -Parent $LauncherPath
if (-not (Test-Path $launcherDir)) {
    New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null
}
$vbsContent = @"
' Auto-generated by install-startup-task.ps1 — re-run that script to update.
' Launches the on-air mic watcher with no visible window.
Dim shell : Set shell = CreateObject("WScript.Shell")
WScript.Quit shell.Run("powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$WatcherPath""", 0, True)
"@
Set-Content -Path $LauncherPath -Value $vbsContent -Encoding ASCII

$action = New-ScheduledTaskAction -Execute 'wscript.exe' `
    -Argument ('//B //Nologo "{0}"' -f $LauncherPath)

# Trigger only on this user's logon.
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1)

# Stop any previous instance before (re)registering so we never end up with
# two watchers posting at once.
try { Stop-ScheduledTask -TaskName $TaskName -ErrorAction Stop } catch {}
Stop-WatcherProcesses

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Settings $settings `
    -Description 'Watches the microphone ConsentStore registry keys and reports active/idle to Home Assistant (on-air light).' `
    -Force | Out-Null

Write-Host "Registered scheduled task '$TaskName' (runs windowless at logon for $env:USERNAME)."

Start-ScheduledTask -TaskName $TaskName
Write-Host 'Started the watcher now. Log file:'
Write-Host "  $env:LOCALAPPDATA\on-air-light\mic_watcher.log"
